# Generated by Django 3.0rc1 on 2020-05-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200502_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('LABORATORY FURNITURE', 'LABORATORY FURNITURE'), ('SURGERY', 'SURGERY'), ('ENDOSCOPY', 'ENDOSCOPY'), ('NEONATOLOGY', 'NEONATOLOGY'), ('CONSUMABLES', 'CONSUMABLES'), ('VETERINARY', 'VETERINARY'), ('PHYSIOTHERAPY', 'PHYSIOTHERAPY'), ('ULTRASOUND DIAGNOSTICS', 'ULTRASOUND DIAGNOSTICS'), ('ENDOCRINOLOGY', 'ENDOCRINOLOGY'), ('STERILIZATION AND DISINFECTION', 'STERILIZATION AND DISINFECTION'), ('DENTISTRY', 'DENTISTRY'), ('CT SCAN', 'CT SCAN'), ('MEDICAL FURNITURE', 'MEDICAL FURNITURE'), ('ANGIOLOGY AND MRI', 'ANGIOLOGY AND MRI'), ('FUNCTIONAL DIAGNOSTICS', 'FUNCTIONAL DIAGNOSTICS'), ('ANESTHESIOLOGY AND RESUSCITATION', 'ANESTHESIOLOGY AND RESUSCITATION'), ('METAL FURNITURE', 'METAL FURNITURE')], default='SURGERY', max_length=50),
        ),
    ]
