# Generated by Django 3.0.7 on 2020-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200502_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('CONSUMABLES', 'CONSUMABLES'), ('PHYSIOTHERAPY', 'PHYSIOTHERAPY'), ('NEONATOLOGY', 'NEONATOLOGY'), ('ANESTHESIOLOGY AND RESUSCITATION', 'ANESTHESIOLOGY AND RESUSCITATION'), ('ENDOSCOPY', 'ENDOSCOPY'), ('ANGIOLOGY AND MRI', 'ANGIOLOGY AND MRI'), ('ULTRASOUND DIAGNOSTICS', 'ULTRASOUND DIAGNOSTICS'), ('FUNCTIONAL DIAGNOSTICS', 'FUNCTIONAL DIAGNOSTICS'), ('LABORATORY FURNITURE', 'LABORATORY FURNITURE'), ('CT SCAN', 'CT SCAN'), ('MEDICAL FURNITURE', 'MEDICAL FURNITURE'), ('VETERINARY', 'VETERINARY'), ('METAL FURNITURE', 'METAL FURNITURE'), ('DENTISTRY', 'DENTISTRY'), ('SURGERY', 'SURGERY'), ('STERILIZATION AND DISINFECTION', 'STERILIZATION AND DISINFECTION'), ('ENDOCRINOLOGY', 'ENDOCRINOLOGY')], default='SURGERY', max_length=50),
        ),
    ]
