# Generated by Django 3.0.7 on 2020-06-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200608_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('MEDICAL FURNITURE', 'MEDICAL FURNITURE'), ('ANESTHESIOLOGY AND RESUSCITATION', 'ANESTHESIOLOGY AND RESUSCITATION'), ('ULTRASOUND DIAGNOSTICS', 'ULTRASOUND DIAGNOSTICS'), ('CONSUMABLES', 'CONSUMABLES'), ('ENDOCRINOLOGY', 'ENDOCRINOLOGY'), ('METAL FURNITURE', 'METAL FURNITURE'), ('CT SCAN', 'CT SCAN'), ('DENTISTRY', 'DENTISTRY'), ('ENDOSCOPY', 'ENDOSCOPY'), ('ANGIOLOGY AND MRI', 'ANGIOLOGY AND MRI'), ('FUNCTIONAL DIAGNOSTICS', 'FUNCTIONAL DIAGNOSTICS'), ('SURGERY', 'SURGERY'), ('STERILIZATION AND DISINFECTION', 'STERILIZATION AND DISINFECTION'), ('LABORATORY FURNITURE', 'LABORATORY FURNITURE'), ('PHYSIOTHERAPY', 'PHYSIOTHERAPY'), ('VETERINARY', 'VETERINARY'), ('NEONATOLOGY', 'NEONATOLOGY')], default='SURGERY', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
