# Generated by Django 3.0.7 on 2020-06-08 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200608_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('FUNCTIONAL DIAGNOSTICS', 'FUNCTIONAL DIAGNOSTICS'), ('VETERINARY', 'VETERINARY'), ('PHYSIOTHERAPY', 'PHYSIOTHERAPY'), ('LABORATORY FURNITURE', 'LABORATORY FURNITURE'), ('CONSUMABLES', 'CONSUMABLES'), ('DENTISTRY', 'DENTISTRY'), ('METAL FURNITURE', 'METAL FURNITURE'), ('ULTRASOUND DIAGNOSTICS', 'ULTRASOUND DIAGNOSTICS'), ('SURGERY', 'SURGERY'), ('CT SCAN', 'CT SCAN'), ('STERILIZATION AND DISINFECTION', 'STERILIZATION AND DISINFECTION'), ('ENDOSCOPY', 'ENDOSCOPY'), ('MEDICAL FURNITURE', 'MEDICAL FURNITURE'), ('ANESTHESIOLOGY AND RESUSCITATION', 'ANESTHESIOLOGY AND RESUSCITATION'), ('NEONATOLOGY', 'NEONATOLOGY'), ('ENDOCRINOLOGY', 'ENDOCRINOLOGY'), ('ANGIOLOGY AND MRI', 'ANGIOLOGY AND MRI')], default='SURGERY', max_length=50),
        ),
    ]
